### ISSUE TITLE
Azureでsshできるものを作る

### ISSUE THREAD

**Issue by FooQoo** [dx-junkyard/secure-interpreter#1]
1. Azure上にDockerコンテナを立てる
2. ターミナルでsshできることを確認する

**Comment by Mitsuo-Koikawa** [comment]
[ServiceLayout.pptx](https://github.com/dx-junkyard/secure-interpreter/files/14634275/ServiceLayout.pptx)
戀川がイメージしているサービスの概略を書きだしました。
